// Generated by Apple Swift version 5.4 (swiftlang-1205.0.26.9 clang-1205.0.19.55)
#ifndef XUWUUIKIT_SWIFT_H
#define XUWUUIKIT_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreGraphics;
@import DZNEmptyDataSet;
@import Foundation;
@import HBDNavigationBar;
@import JXSegmentedView;
@import ObjectiveC;
@import QuartzCore;
@import TangramKit;
@import UIKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="XuwuUIKit",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

@class NSCoder;

SWIFT_CLASS("_TtC9XuwuUIKit10SLBaseView")
@interface SLBaseView : TGRelativeLayout
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (void)configUI;
@end

@class NSString;

SWIFT_CLASS("_TtC9XuwuUIKit11SLAlertView")
@interface SLAlertView : SLBaseView
- (void)configWithTitle:(NSString * _Nullable)title message:(NSString * _Nullable)message cancel:(NSString * _Nullable)cancel confirm:(NSString * _Nullable)confirm;
@property (nonatomic, copy) void (^ _Nullable cancelBlock)(void);
@property (nonatomic, copy) void (^ _Nullable confirmBlock)(void);
- (void)configUI;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end


@class NSNumber;

SWIFT_CLASS("_TtC9XuwuUIKit17SLAutoScrollLabel")
@interface SLAutoScrollLabel : UIView
/// 是否自动滚动 文本宽度大于父容器 自动滚动，否则不滚动
@property (nonatomic) BOOL isAutoScroll;
- (void)layoutSubviews;
@property (nonatomic) BOOL isPaused;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)scrollTexts:(NSArray<NSString *> * _Nonnull)texts;
- (void)resume;
- (void)stop;
@end


SWIFT_CLASS("_TtC9XuwuUIKit20SLBaseCollectionCell")
@interface SLBaseCollectionCell : UICollectionViewCell
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (void)configUI;
@end


SWIFT_CLASS("_TtC9XuwuUIKit28SLBaseCollectionReusableView")
@interface SLBaseCollectionReusableView : UICollectionReusableView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (void)configUI;
@end

@class UIImage;
@class UIColor;
@class NSBundle;

SWIFT_CLASS("_TtC9XuwuUIKit20SLBaseViewController")
@interface SLBaseViewController : UIViewController
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) UIImage * _Nullable backImage;)
+ (UIImage * _Nullable)backImage SWIFT_WARN_UNUSED_RESULT;
+ (void)setBackImage:(UIImage * _Nullable)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) UIImage * _Nullable emptyImage;)
+ (UIImage * _Nullable)emptyImage SWIFT_WARN_UNUSED_RESULT;
+ (void)setEmptyImage:(UIImage * _Nullable)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nullable emptyString;)
+ (NSString * _Nullable)emptyString SWIFT_WARN_UNUSED_RESULT;
+ (void)setEmptyString:(NSString * _Nullable)value;
- (void)loadView;
- (void)viewDidLoad;
- (void)configImageBack:(UIImage * _Nullable)image tintColor:(UIColor * _Nonnull)tintColor;
/// 设置标题颜色
@property (nonatomic, strong) UIColor * _Nullable titleColor;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIScrollView;

SWIFT_CLASS("_TtC9XuwuUIKit24SLBaseListViewController")
@interface SLBaseListViewController : SLBaseViewController
@property (nonatomic, copy) NSArray * _Nonnull dataAry;
@property (nonatomic) int32_t pageIndex;
@property (nonatomic) int32_t pageSize;
@property (nonatomic) BOOL isHiddenRefresh;
- (void)loadWithRefresh:(BOOL)refresh more:(BOOL)more scrollView:(UIScrollView * _Nonnull)scrollView;
- (void)loadMore:(BOOL)more;
- (void)beginRefreshing;
- (void)endHeaderFooterRefreshing;
- (void)noMoreData;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UICollectionView;

SWIFT_CLASS("_TtC9XuwuUIKit30SLBaseCollectionViewController")
@interface SLBaseCollectionViewController : SLBaseListViewController
- (void)loadWithRefresh:(BOOL)refresh more:(BOOL)more;
@property (nonatomic, strong) UICollectionView * _Nonnull mCollectionView;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class NSIndexPath;

@interface SLBaseCollectionViewController (SWIFT_EXTENSION(XuwuUIKit)) <UICollectionViewDataSource>
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UICollectionViewCell * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC9XuwuUIKit22SLBaseHeaderFooterView")
@interface SLBaseHeaderFooterView : UITableViewHeaderFooterView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithReuseIdentifier:(NSString * _Nullable)reuseIdentifier SWIFT_UNAVAILABLE;
- (void)configUI;
@end



@interface SLBaseListViewController (SWIFT_EXTENSION(XuwuUIKit)) <DZNEmptyDataSetDelegate>
- (BOOL)emptyDataSetShouldAllowScroll:(UIScrollView * _Null_unspecified)scrollView SWIFT_WARN_UNUSED_RESULT;
@end


@interface SLBaseListViewController (SWIFT_EXTENSION(XuwuUIKit)) <DZNEmptyDataSetSource>
- (UIView * _Null_unspecified)customViewForEmptyDataSet:(UIScrollView * _Null_unspecified)scrollView SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC9XuwuUIKit26SLBaseNavigationController")
@interface SLBaseNavigationController : HBDNavigationController
- (void)viewDidLoad;
- (void)pushViewController:(UIViewController * _Nonnull)viewController animated:(BOOL)animated;
- (nonnull instancetype)initWithNavigationBarClass:(Class _Nullable)navigationBarClass toolbarClass:(Class _Nullable)toolbarClass OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=5.0);
- (nonnull instancetype)initWithRootViewController:(UIViewController * _Nonnull)rootViewController OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIGestureRecognizer;

@interface SLBaseNavigationController (SWIFT_EXTENSION(XuwuUIKit)) <UIGestureRecognizerDelegate>
- (BOOL)gestureRecognizerShouldBegin:(UIGestureRecognizer * _Nonnull)gestureRecognizer SWIFT_WARN_UNUSED_RESULT;
- (BOOL)gestureRecognizer:(UIGestureRecognizer * _Nonnull)gestureRecognizer shouldRecognizeSimultaneouslyWithGestureRecognizer:(UIGestureRecognizer * _Nonnull)otherGestureRecognizer SWIFT_WARN_UNUSED_RESULT;
@end

@class JXSegmentedView;
@class JXSegmentedListContainerView;

SWIFT_CLASS("_TtC9XuwuUIKit27SLBaseSegmentViewController")
@interface SLBaseSegmentViewController : SLBaseViewController
@property (nonatomic, copy) NSArray * _Nonnull dataAry;
- (void)loadSegmentedData;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
@property (nonatomic, strong) JXSegmentedView * _Nonnull segmentedView;
@property (nonatomic, strong) JXSegmentedListContainerView * _Nonnull containerView;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@protocol JXSegmentedListContainerViewListDelegate;

@interface SLBaseSegmentViewController (SWIFT_EXTENSION(XuwuUIKit)) <JXSegmentedListContainerViewDataSource>
- (NSInteger)numberOfListsIn:(JXSegmentedListContainerView * _Nonnull)listContainerView SWIFT_WARN_UNUSED_RESULT;
- (id <JXSegmentedListContainerViewListDelegate> _Nonnull)listContainerView:(JXSegmentedListContainerView * _Nonnull)listContainerView initListAt:(NSInteger)index SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC9XuwuUIKit15SLBaseTableCell")
@interface SLBaseTableCell : UITableViewCell
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier SWIFT_UNAVAILABLE;
- (void)configUI;
@end

@class UITableView;

SWIFT_CLASS("_TtC9XuwuUIKit25SLBaseTableViewController")
@interface SLBaseTableViewController : SLBaseListViewController
- (nonnull instancetype)initWithStyle:(enum UITableViewStyle)style OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (void)loadWithRefresh:(BOOL)refresh more:(BOOL)more;
@property (nonatomic, strong) UITableView * _Nonnull mTableView;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end


@interface SLBaseTableViewController (SWIFT_EXTENSION(XuwuUIKit)) <UITableViewDataSource>
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end




@interface SLBaseViewController (SWIFT_EXTENSION(XuwuUIKit)) <JXSegmentedListContainerViewListDelegate>
- (UIView * _Nonnull)listView SWIFT_WARN_UNUSED_RESULT;
@end

@class UIFont;

SWIFT_CLASS("_TtC9XuwuUIKit11SLHorseView")
@interface SLHorseView : UIView
@property (nonatomic, copy) NSString * _Nullable text;
@property (nonatomic, strong) UIColor * _Nonnull textColor;
@property (nonatomic, strong) UIFont * _Nullable textFont;
@property (nonatomic, strong) UIColor * _Nonnull gradientColor;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
- (void)layoutSubviews;
@end

@class NSTextContainer;

SWIFT_CLASS("_TtC9XuwuUIKit11SLInputView")
@interface SLInputView : UITextView
/// 最大行数
@property (nonatomic) NSInteger maxLine;
/// 字数限制
@property (nonatomic) NSInteger limit;
/// 占位文本
@property (nonatomic, copy) NSString * _Nonnull placeholder;
/// 占位文本颜色
@property (nonatomic, strong) UIColor * _Nonnull placeholderColor;
/// 占位文本字体
@property (nonatomic, strong) UIFont * _Nullable placeholderFont;
/// 高度变化回调
@property (nonatomic, copy) void (^ _Nullable heightChangeBlock)(SLInputView * _Nonnull);
/// 文本变化回调
@property (nonatomic, copy) void (^ _Nullable textChangeBlock)(SLInputView * _Nonnull);
- (void)layoutSubviews;
- (void)reset;
- (void)textChange;
- (nonnull instancetype)initWithFrame:(CGRect)frame textContainer:(NSTextContainer * _Nullable)textContainer SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC9XuwuUIKit10SLMenuView")
@interface SLMenuView : SLBaseView
@property (nonatomic) Class _Nonnull menuItemCellType;
@property (nonatomic) CGFloat menuItemHeight;
@property (nonatomic, copy) void (^ _Nullable menuSelectedBlock)(NSInteger);
/// 显示菜单
/// \param view 弹出的父view
///
- (void)showIn:(UIView * _Nonnull)view;
- (void)dissmiss;
- (void)configUI;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end


@interface SLMenuView (SWIFT_EXTENSION(XuwuUIKit)) <UITableViewDataSource, UITableViewDelegate>
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end


SWIFT_CLASS("_TtC9XuwuUIKit11SLPopupView")
@interface SLPopupView : TGRelativeLayout
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic) UIEdgeInsets padding;
@property (nonatomic) CGFloat popupRadius;
/// 是否需要蒙层
@property (nonatomic) BOOL maskNeed;
/// 蒙层是否接收点击事件
@property (nonatomic) BOOL maskTouch;
/// 点击蒙层是否隐藏弹窗
@property (nonatomic) BOOL maskTouchDismiss;
- (void)dismissWithComplete:(void (^ _Nullable)(void))complete;
@end


SWIFT_CLASS("_TtC9XuwuUIKit13SLSuspendView")
@interface SLSuspendView : UIView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@property (nonatomic, strong) UIView * _Nonnull contentView;
@property (nonatomic) BOOL isKeepBounds;
@property (nonatomic) BOOL isDragEnable;
@property (nonatomic) CGRect freeRect;
@property (nonatomic, copy) void (^ _Nullable clickBlock)(SLSuspendView * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable dragBegainBlock)(SLSuspendView * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable dragChangeBlock)(SLSuspendView * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable dragEndBlock)(SLSuspendView * _Nonnull);
@end


SWIFT_CLASS("_TtC9XuwuUIKit11SLToastView")
@interface SLToastView : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) SLToastView * _Nonnull shared;)
+ (SLToastView * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (void)hideToastActivity;
- (void)alertWithTitle:(NSString * _Nullable)title message:(NSString * _Nullable)message messageColor:(UIColor * _Nullable)messageColor cancel:(NSString * _Nullable)cancel confirm:(NSString * _Nullable)confirm cancelBlock:(void (^ _Nullable)(void))cancelBlock confirmBlock:(void (^ _Nullable)(void))confirmBlock;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// 麦位波浪
SWIFT_CLASS("_TtC9XuwuUIKit10SLWaveView")
@interface SLWaveView : UIView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithColor:(UIColor * _Nonnull)color radius:(CGFloat)radius count:(NSInteger)count timeInterval:(NSTimeInterval)timeInterval duration:(NSTimeInterval)duration repeatCount:(float)repeatCount OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic) BOOL isAnimating;
/// 开始动画
- (void)start;
/// 结束动画
- (void)stop;
- (void)layoutSubviews;
@end

@class CAAnimation;

@interface SLWaveView (SWIFT_EXTENSION(XuwuUIKit)) <CAAnimationDelegate>
- (void)animationDidStart:(CAAnimation * _Nonnull)anim;
- (void)animationDidStop:(CAAnimation * _Nonnull)anim finished:(BOOL)flag;
@end















@interface UIView (SWIFT_EXTENSION(XuwuUIKit))
- (void)rl_setImage:(NSString * _Nonnull)name;
- (void)rl_setSelectedImage:(NSString * _Nonnull)name;
- (void)rl_setText:(NSString * _Nonnull)text;
- (void)rl_setTextAligin:(int32_t)textAligin;
- (void)rl_setColor:(UIColor * _Nonnull)color;
- (void)rl_setFont:(NSString * _Nonnull)name size:(CGFloat)size;
@end




#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif
